services:
  authservice:
    ports:
      - "5078:8080"

  flightservice:
    ports:
      - "5162:8080"

  reservationservice:
    ports:
      - "5029:8080"

  availabilityservice:
    ports:
      - "5099:8080"

  paymentservice:
    ports:
      - "5088:8080"

  notificationservice:
    ports:
      - "5118:8080"
